services:
  # 1. Base de datos NoSQL para tus leyendas
  db:
    image: mongo:latest
    container_name: leyendas_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # 2. API en Python
  backend:
    build: ./backend
    container_name: leyendas_backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://db:27017/
    depends_on:
      - db
    develop:
      watch:
        # Sincroniza todo lo que cambies dentro de la carpeta local ./backend 
        # directamente en la carpeta /app del contenedor
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - __pycache__/
            - .pytest_cache/
        
        # Si agregas una librería a requirements.txt, Docker reconstruirá la imagen sola
        - action: rebuild
          path: ./backend/requirements.txt

  # 3. Frontend en React (Vite + TypeScript)
  frontend:
    build: ./frontend
    container_name: leyendas_frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    stdin_open: true
    tty: true
    depends_on:
      - backend
    # ¡ESTE BLOQUE AHORA ESTÁ DENTRO DE FRONTEND!
    develop:
      watch:
        # 1. Sincronizar (Sync): Copia el archivo al contenedor sin reiniciarlo
        - action: sync
          path: ./frontend/src
          target: /app/src
          ignore:
            - node_modules/
        # 2. Reconstruir (Rebuild): Reconstruye la imagen si cambian las dependencias
        - action: rebuild
          path: ./frontend/package.json

volumes:
  mongo_data: